import type { Car, MockUser, RecentSearch } from "./types"

// -----------------------------------------------------------------------------
// DEMONSTRATION DATA ONLY. Every listing below is a hardcoded fixture used to
// prototype the BuySeconds experience. Nothing here is fetched from a real
// marketplace, and availability/pricing must never be presented as current.
// -----------------------------------------------------------------------------

export const MOCK_CARS: Car[] = [
  {
    id: "car-01",
    make: "Maruti Suzuki",
    model: "Swift",
    variant: "VXI AMT",
    year: 2021,
    fuelType: "Petrol",
    transmission: "Automatic",
    price: 620000,
    kilometres: 28500,
    city: "Bengaluru",
    image: "/mock-cars/maruti-swift.png",
    marketplaceName: "CarWheel Marketplace",
    sourceUrl: "https://example.com/listings/car-01",
    sellerType: "Certified Dealer",
    postedDate: "2024-11-02",
    availability: "Available",
    features: ["Touchscreen infotainment", "Rear parking sensors", "ABS with EBD"],
    description:
      "Well-maintained single-owner hatchback, serviced on schedule at an authorised centre.",
    conditionNotes: "Minor door-edge scuff on the front passenger side, disclosed by seller.",
  },
  {
    id: "car-02",
    make: "Hyundai",
    model: "Creta",
    variant: "SX Diesel",
    year: 2020,
    fuelType: "Diesel",
    transmission: "Manual",
    price: 1350000,
    kilometres: 41200,
    city: "Mumbai",
    image: "/mock-cars/hyundai-creta.png",
    marketplaceName: "DriveNext",
    sourceUrl: "https://example.com/listings/car-02",
    sellerType: "Dealer",
    postedDate: "2024-10-18",
    availability: "Available",
    features: ["Sunroof", "Ventilated seats", "Cruise control", "Wireless charging"],
    description: "Highway-driven SUV with full service history and recent brake replacement.",
    conditionNotes: "Tyres replaced within the last 6,000 km.",
  },
  {
    id: "car-03",
    make: "Honda",
    model: "City",
    variant: "V CVT",
    year: 2022,
    fuelType: "Petrol",
    transmission: "Automatic",
    price: 1120000,
    kilometres: 15800,
    city: "Pune",
    image: "/mock-cars/honda-city.png",
    marketplaceName: "CarWheel Marketplace",
    sourceUrl: "https://example.com/listings/car-03",
    sellerType: "Certified Dealer",
    postedDate: "2024-12-05",
    availability: "Available",
    features: ["Lane watch camera", "Sunroof", "Auto climate control"],
    description: "Low-mileage sedan, first owner, garage-parked.",
    conditionNotes: "No accident history reported.",
  },
  {
    id: "car-04",
    make: "Tata",
    model: "Nexon",
    variant: "XZ+ Petrol",
    year: 2021,
    fuelType: "Petrol",
    transmission: "Manual",
    price: 850000,
    kilometres: 32000,
    city: "Delhi",
    image: "/mock-cars/tata-nexon.png",
    marketplaceName: "SecondDrive",
    sourceUrl: "https://example.com/listings/car-04",
    sellerType: "Individual",
    postedDate: "2024-09-27",
    availability: "Available",
    features: ["5-star safety rating", "Rear camera", "Push-button start"],
    description: "City-driven compact SUV, sold by original owner relocating abroad.",
    conditionNotes: "Small windshield chip, repaired.",
  },
  {
    id: "car-05",
    make: "Mahindra",
    model: "XUV700",
    variant: "AX7 Diesel",
    year: 2023,
    fuelType: "Diesel",
    transmission: "Automatic",
    price: 2450000,
    kilometres: 9800,
    city: "Hyderabad",
    image: "/mock-cars/mahindra-xuv700.png",
    marketplaceName: "DriveNext",
    sourceUrl: "https://example.com/listings/car-05",
    sellerType: "Dealer",
    postedDate: "2024-12-20",
    availability: "Available",
    features: ["ADAS", "Panoramic sunroof", "3-row seating", "360-degree camera"],
    description: "Nearly new flagship SUV still under manufacturer warranty.",
    conditionNotes: "Showroom condition, single owner.",
  },
  {
    id: "car-06",
    make: "Maruti Suzuki",
    model: "Baleno",
    variant: "Delta",
    year: 2019,
    fuelType: "Petrol",
    transmission: "Manual",
    price: 560000,
    kilometres: 52400,
    city: "Chennai",
    image: "/mock-cars/maruti-baleno.png",
    marketplaceName: "SecondDrive",
    sourceUrl: "https://example.com/listings/car-06",
    sellerType: "Individual",
    postedDate: "2024-08-14",
    availability: "Available",
    features: ["Automatic climate control", "Touchscreen infotainment"],
    description: "Budget-friendly premium hatchback with consistent service records.",
    conditionNotes: "Rear bumper repainted after a minor parking scrape.",
  },
  {
    id: "car-07",
    make: "Kia",
    model: "Seltos",
    variant: "GTX+ Turbo",
    year: 2022,
    fuelType: "Petrol",
    transmission: "Automatic",
    price: 1580000,
    kilometres: 21300,
    city: "Bengaluru",
    image: "/mock-cars/kia-seltos.png",
    marketplaceName: "CarWheel Marketplace",
    sourceUrl: "https://example.com/listings/car-07",
    sellerType: "Certified Dealer",
    postedDate: "2024-11-29",
    availability: "Available",
    features: ["Turbo petrol engine", "Bose sound system", "Ventilated seats"],
    description: "Sporty top-trim SUV with turbocharged engine, dealer certified.",
    conditionNotes: "150-point inspection passed.",
  },
  {
    id: "car-08",
    make: "Toyota",
    model: "Innova Crysta",
    variant: "GX Diesel",
    year: 2020,
    fuelType: "Diesel",
    transmission: "Manual",
    price: 1750000,
    kilometres: 68000,
    city: "Ahmedabad",
    image: "/mock-cars/toyota-innova.png",
    marketplaceName: "DriveNext",
    sourceUrl: "https://example.com/listings/car-08",
    sellerType: "Dealer",
    postedDate: "2024-07-30",
    availability: "Available",
    features: ["7-seater", "Captain seats", "Rear AC vents"],
    description: "Fleet-maintained family MPV, higher kilometres but strong reliability record.",
    conditionNotes: "Timing belt and clutch replaced at last major service.",
  },
  {
    id: "car-09",
    make: "MG",
    model: "ZS EV",
    variant: "Exclusive",
    year: 2021,
    fuelType: "Electric",
    transmission: "Automatic",
    price: 1650000,
    kilometres: 18500,
    city: "Pune",
    image: "/mock-cars/mg-zs-ev.png",
    marketplaceName: "SecondDrive",
    sourceUrl: "https://example.com/listings/car-09",
    sellerType: "Individual",
    postedDate: "2024-10-02",
    availability: "Available",
    features: ["Battery health report included", "Fast charging", "Panoramic sunroof"],
    description: "Early adopter EV, home-charged, includes original charger and cable.",
    conditionNotes: "Battery health reported at 94% of rated capacity.",
  },
  {
    id: "car-10",
    make: "Hyundai",
    model: "Venue",
    variant: "SX(O) Turbo",
    year: 2020,
    fuelType: "Petrol",
    transmission: "Manual",
    price: 780000,
    kilometres: 39600,
    city: "Delhi",
    image: "/mock-cars/hyundai-venue.png",
    marketplaceName: "CarWheel Marketplace",
    sourceUrl: "https://example.com/listings/car-10",
    sellerType: "Certified Dealer",
    postedDate: "2024-09-08",
    availability: "Available",
    features: ["BlueLink connected car tech", "Sunroof", "Turbo petrol engine"],
    description: "Feature-loaded compact SUV, top variant with turbo engine.",
    conditionNotes: "One insurance claim on record for a minor rear-end incident.",
  },
]

export const MOCK_USERS: MockUser[] = [
  {
    id: "user-01",
    name: "Asha Rao",
    email: "asha@example.com",
    password: "password123",
    defaultCity: "Bengaluru",
  },
  {
    id: "user-02",
    name: "Demo Customer",
    email: "demo@buyseconds.com",
    password: "demo1234",
    defaultCity: "Mumbai",
  },
]

export const BRANDS = Array.from(new Set(MOCK_CARS.map((car) => car.make))).sort()

export const CITIES = Array.from(new Set(MOCK_CARS.map((car) => car.city))).sort()

export const FUEL_TYPES = Array.from(new Set(MOCK_CARS.map((car) => car.fuelType)))

// Seed fixture used only until a real customer performs their own searches.
export const SEED_RECENT_SEARCHES: RecentSearch[] = [
  {
    id: "search-01",
    criteria: { city: "Bengaluru", brand: "Maruti Suzuki", maxPrice: 700000 },
    label: "Maruti Suzuki in Bengaluru, under ₹7L",
    createdAt: "2024-12-18T09:30:00.000Z",
    resultCount: 5,
  },
  {
    id: "search-02",
    criteria: { city: "Pune", fuelType: "Petrol", maxAgeYears: 4 },
    label: "Petrol cars in Pune, under 4 years old",
    createdAt: "2024-12-14T14:05:00.000Z",
    resultCount: 5,
  },
  {
    id: "search-03",
    criteria: { city: "Delhi", maxPrice: 900000, maxKilometres: 40000 },
    label: "Delhi, under ₹9L and 40,000 km",
    createdAt: "2024-12-10T11:20:00.000Z",
    resultCount: 5,
  },
]
